"""added user column

Revision ID: fff9be57260e
Revises: 6dfe95eb5098
Create Date: 2021-09-24 13:51:43.833432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff9be57260e'
down_revision = '6dfe95eb5098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
