version: '3.3'

services:
    person_fastapi:
        image: "${CONTAINER_REGISTRY}/analystt/person_fastapi:latest"
        container_name: "person_fastapi"
        ports:
            - "8000:5000"
            
    person_react:
        image: "${CONTAINER_REGISTRY}/analystt/person_react:latest"
        container_name: "person_react"      
        ports: 
            - 80:80
            