version: '3.3'
# React on port 8000 and fastapi on port 5000
services:
    person_fastapi:
        image: "analystt/person_fastapi:latest"
        container_name: "person_fastapi"
        ports:
            - 12001:5000
    
    person_react:
        image: "analystt/person_react:latest"
        container_name: "person_react"
        ports: 
            - 12002:80
        depends_on:
            - person_fastapi
