version: '3.3'

services:
    selenium:
        image: "selenium/standalone-chrome:latest"
        container_name: "selenium"
        ports:
            - "4445:4444"
        volumes:
            - /dev/shm:/dev/shm

    person_fastapi:
        image: "analystt/person_fastapi:latest"
        container_name: "person_fastapi"
        ports:
            - 12001:5000
        environment:
            - APP_CONFIG_SELENIUM_SERVER_URL=http://selenium:4444/wd/hub
    
    person_react:
        image: "analystt/person_react:latest"
        container_name: "person_react"
        ports: 
            - 12002:80
        depends_on:
            - person_fastapi
