# Generated by Django 3.1.7 on 2021-06-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upoad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetable',
            name='datetime',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
