# Generated by Django 3.1.7 on 2021-06-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upoad', '0005_filetable_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetable',
            name='url',
        ),
        migrations.AddField(
            model_name='filetable',
            name='col_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
