"""added modified column

Revision ID: 1d0cc4aed32f
Revises: 4ea2fe98a60d
Create Date: 2021-09-23 06:51:12.437163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0cc4aed32f'
down_revision = '4ea2fe98a60d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_credit_history', sa.Column('modified_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_credit_history', 'modified_on')
    # ### end Alembic commands ###
