"""added users table

Revision ID: 312d81744ee0
Revises: c3084a4a91ac
Create Date: 2021-09-22 17:41:31.031654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312d81744ee0'
down_revision = 'c3084a4a91ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_credit_history', sa.Column('modified_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_credit_history', 'modified_on')
    # ### end Alembic commands ###
