"""check migration3

Revision ID: 4ea2fe98a60d
Revises: 8cb17073337f
Create Date: 2021-09-23 06:16:42.060339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea2fe98a60d'
down_revision = '8cb17073337f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
