"""deleted modified column

Revision ID: 6dfe95eb5098
Revises: 1d0cc4aed32f
Create Date: 2021-09-23 17:11:26.641429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6dfe95eb5098'
down_revision = '1d0cc4aed32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_credit_history', 'modified_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_credit_history', sa.Column('modified_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
