"""check migration2

Revision ID: 8cb17073337f
Revises: 902191a9e3d3
Create Date: 2021-09-22 18:51:47.797604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb17073337f'
down_revision = '902191a9e3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
