"""check migration

Revision ID: 902191a9e3d3
Revises: d728518e00e7
Create Date: 2021-09-22 18:41:07.473412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902191a9e3d3'
down_revision = 'd728518e00e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
