"""removed modified date from  credit hostory

Revision ID: d728518e00e7
Revises: 312d81744ee0
Create Date: 2021-09-22 17:47:33.438406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd728518e00e7'
down_revision = '312d81744ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_credit_history', 'modified_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_credit_history', sa.Column('modified_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
