# Generated by Django 3.1.7 on 2021-06-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upoad', '0002_auto_20210608_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetable',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
