# Generated by Django 3.1.7 on 2021-06-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upoad', '0003_filetable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetable',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
