# Generated by Django 3.1.7 on 2021-06-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_auto_20210611_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagtable',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='tagtable',
            name='display',
        ),
        migrations.RemoveField(
            model_name='tagtable',
            name='value',
        ),
        migrations.AlterField(
            model_name='tagtable',
            name='name',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
