# Generated by Django 3.1.7 on 2021-06-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_auto_20210611_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtable',
            name='status',
            field=models.CharField(blank=True, default='Not verified', max_length=10, null=True),
        ),
    ]
