# Generated by Django 3.1.7 on 2021-06-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0006_auto_20210624_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtable',
            name='organization',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
