# Generated by Django 3.1.7 on 2021-06-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_auto_20210612_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtable',
            name='status',
            field=models.CharField(blank=True, default='Not verified', max_length=50, null=True),
        ),
    ]
