"""database updates at 1632574145

Revision ID: 2eac67ee0384
Revises: 65ece1075297
Create Date: 2021-09-25 12:49:07.696641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eac67ee0384'
down_revision = '65ece1075297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
