"""database updates at 1632559954

Revision ID: 65ece1075297
Revises: 2c774fc04480
Create Date: 2021-09-25 08:52:36.857419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ece1075297'
down_revision = '2c774fc04480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
