"""database updates at 1632575813

Revision ID: ad6d8cd524e8
Revises: 2eac67ee0384
Create Date: 2021-09-25 13:16:55.636268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6d8cd524e8'
down_revision = '2eac67ee0384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
