TEST_CONFIG_API_BASE_URL = "http://localhost:12005"
TEST_CONFIG_API_USER_HEADERS = (
    {
        "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiY2FjMWNhZTEtMWFmNC00MTEwLWIwYzYtZWJlZjM1NWM5M2I5IiwiYXVkIjpbImZhc3RhcGktdXNlcnM6YXV0aCJdLCJleHAiOjE2Mjk4NDY0NDh9.IzrLBcq2TydPv3Ull_tboR8j7hJ4rui9UfaPGzHdJfU"
    },
)
